// prisma/seed.ts
import { PrismaClient, Prisma } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("ðŸŒ± Iniciando seed...");

  // â”€â”€ Certame de teste 2026 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  const certame2026 = await prisma.certame.upsert({
    where: { year: 2026 },
    update: {},
    create: {
      year: 2026,
      periodoInicio: new Date("2025-01-01"),
      periodoFim: new Date("2026-12-31"),
      isActive: true,
      isClosed: false,                    // âœ… campo agora existe no schema
    },
  });
  console.log("âœ… Certame 2026 criado:", certame2026.id);

  // â”€â”€ UsuÃ¡rio admin padrÃ£o â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  const passwordHash = await bcrypt.hash("Admin@2026!", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@rcbambiental.com.br" },
    update: {},
    create: {
      email: "admin@rcbambiental.com.br",
      name: "Camila Loiola",
      passwordHash,
      role: "admin",                      // âœ… enum lowercase (schema: admin/employee)
      mustChangePassword: true,           // âœ… campo agora existe no schema
      isActive: true,                     // âœ… campo agora existe no schema
    },
  });
  console.log("âœ… Admin criado:", admin.email);

  // â”€â”€ CritÃ©rios do Decreto 24.288/2025 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  const criteria = [
    // â”€â”€ A â€” Gerenciamento de ResÃ­duos SÃ³lidos â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "A.1",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "DestinaÃ§Ã£o final ambientalmente adequada de resÃ­duos em aterro sanitÃ¡rio",
      requirement: "DestinaÃ§Ã£o final ambientalmente adequada de resÃ­duos em aterro sanitÃ¡rio, em funcionamento, de acordo com as normas tÃ©cnicas.",
      requiredDocs: "CÃ³pia da LicenÃ§a de OperaÃ§Ã£o (LO) do aterro sanitÃ¡rio receptor vigente durante todo o perÃ­odo de apuraÃ§Ã£o + CÃ³pia do Contrato ou instrumento de parceria vigente com o aterro sanitÃ¡rio ou com a empresa responsÃ¡vel pelo transporte e destinaÃ§Ã£o final + Prova da Efetiva e ContÃ­nua DestinaÃ§Ã£o: Manifestos de Transporte de ResÃ­duos (MTR) ou ComprovaÃ§Ã£o Fiscal do ServiÃ§o + Comprovante de cadastro do municÃ­pio no SINIR.",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 1,
    },
    {
      id: "A.2",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Coleta seletiva com adequada destinaÃ§Ã£o",
      requirement: "Possuir serviÃ§o regular de coleta seletiva e adequada destinaÃ§Ã£o.",
      requiredDocs: "Instrumento de planejamento (projeto tÃ©cnico ou programa) + RelatÃ³rio Operacional contendo descriÃ§Ã£o das aÃ§Ãµes com registro fotogrÃ¡fico datado + ComprovaÃ§Ã£o de destinaÃ§Ã£o para cooperativas, comÃ©rcios atacadistas dos resÃ­duos coletados ou correlatos.",
      maxPoints: 14,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 2,
    },
    {
      id: "A.3",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Coleta, transbordo e limpeza pÃºblica (varriÃ§Ã£o, capina e poda)",
      requirement: "Possuir serviÃ§o regular de coleta, transbordo e transporte de resÃ­duos sÃ³lidos e de limpeza pÃºblica abrangendo varriÃ§Ã£o, capina e poda de Ã¡rvores em vias e logradouros pÃºblicos.",
      requiredDocs: "RelatÃ³rio Operacional do perÃ­odo de apuraÃ§Ã£o, discriminando a execuÃ§Ã£o de cada serviÃ§o, registro fotogrÃ¡fico com informaÃ§Ãµes de data e georreferenciamento sobreposto a imagem.",
      maxPoints: 14,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 3,
    },
    {
      id: "A.4",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Coleta e destinaÃ§Ã£o de resÃ­duos de saÃºde (RSS)",
      requirement: "Possuir serviÃ§o regular de coleta, transbordo e transporte de resÃ­duos de serviÃ§o de saÃºde.",
      requiredDocs: "LicenÃ§a Ambiental de OperaÃ§Ã£o ou documento equivalente vÃ¡lidos da empresa contratada para a coleta e o transporte dos resÃ­duos de serviÃ§o de saÃºde + Documento que comprove a destinaÃ§Ã£o final ambientalmente adequada, tal como Manifesto de Transporte de ResÃ­duos.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 4,
    },
    {
      id: "A.5",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Plano Municipal de GestÃ£o Integrada de ResÃ­duos SÃ³lidos",
      requirement: "Plano Municipal de GestÃ£o Integrada de ResÃ­duos SÃ³lidos.",
      requiredDocs: "ApresentaÃ§Ã£o do plano, ou plano simplificado (para municÃ­pios com menos de vinte mil habitantes) ou plano de saneamento bÃ¡sico conforme a PolÃ­tica Nacional de ResÃ­duos SÃ³lidos, inclusive atualizaÃ§Ã£o, com a respectiva publicaÃ§Ã£o.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 5,
    },
    {
      id: "A.6",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Pontos de entrega voluntÃ¡ria (PEVs) de reciclÃ¡veis",
      requirement: "Possuir local de entrega voluntÃ¡ria de resÃ­duos sÃ³lidos reciclÃ¡veis, e comprovada destinaÃ§Ã£o.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o dos pontos de entrega, endereÃ§o, descriÃ§Ã£o do quantitativo recebido e registros fotogrÃ¡ficos de cada ponto de entrega + ComprovaÃ§Ã£o de destinaÃ§Ã£o para cooperativas ou comÃ©rcios atacadistas dos resÃ­duos coletados.",
      maxPoints: 12,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 6,
    },
    {
      id: "A.7",
      axis: "A",
      axisName: "Gerenciamento de ResÃ­duos SÃ³lidos",
      axisMinPoints: 50,
      description: "Parceria com cooperativas de catadores",
      requirement: "AÃ§Ãµes de incentivo e estÃ­mulo Ã s cooperativas, associaÃ§Ãµes e/ou outras modalidades de mobilizaÃ§Ã£o de trabalhadores de coleta e seleÃ§Ã£o de materiais reciclÃ¡veis.",
      requiredDocs: "Contrato, convÃªnio ou outro instrumento de parceria com entidade de direito privado que reÃºna trabalhadores de coleta e seleÃ§Ã£o de materiais reciclÃ¡veis + projeto ou outro documento de planejamento + relatÃ³rio operacional descrevendo as aÃ§Ãµes desenvolvidas.",
      maxPoints: 13,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 7,
    },

    // â”€â”€ B â€” EducaÃ§Ã£o Ambiental â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "B.1",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "CapacitaÃ§Ã£o de recursos humanos municipais (dimensÃ£o ambiental)",
      requirement: "CapacitaÃ§Ã£o de recursos humanos municipais sobre dimensÃ£o ambiental.",
      requiredDocs: "RelatÃ³rio Operacional de cursos, palestras ou treinamentos (com fotos, ementa, data, carga horÃ¡ria, dados do educador e lista de frequÃªncia) voltados aos servidores do municÃ­pio. Somente serÃ¡ admitida a contagem de 3h por servidor.",
      maxPoints: 8,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 8,
    },
    {
      id: "B.2",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "FormaÃ§Ã£o complementar de professores (dimensÃ£o ambiental)",
      requirement: "FormaÃ§Ã£o complementar de professores voltada Ã  dimensÃ£o ambiental.",
      requiredDocs: "RelatÃ³rio Operacional de cursos, palestras e treinamentos (com fotos, ementa, data, carga horÃ¡ria, dados do instrutor e lista de frequÃªncia) voltados aos professores do municÃ­pio. Somente serÃ¡ admitida a contagem de 3h por servidor.",
      maxPoints: 8,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 9,
    },
    {
      id: "B.3",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Treinamento de tÃ©cnicos do Ã³rgÃ£o de meio ambiente",
      requirement: "Treinamento de tÃ©cnicos e gestores do Ã³rgÃ£o local de meio ambiente.",
      requiredDocs: "RelatÃ³rio Operacional de cursos, palestras e treinamentos (com fotos, ementa, data, carga horÃ¡ria, dados do instrutor e lista de frequÃªncia) voltados aos profissionais do Ã³rgÃ£o municipal de meio ambiente.",
      maxPoints: 10,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 10 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 10,
    },
    {
      id: "B.4",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Estudos e pesquisas com ISSN/ISBN",
      requirement: "Desenvolvimento de estudos e pesquisas relacionados Ã  dimensÃ£o ambiental.",
      requiredDocs: "PublicaÃ§Ã£o, pelo municÃ­pio ou por ele financiado, de estudos por meio de artigos cientÃ­ficos, resumos, livros ou publicaÃ§Ãµes cientÃ­ficas, com ISSN/ISBN.",
      maxPoints: 8,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 11,
    },
    {
      id: "B.5",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Material educativo impresso ou campanha digital",
      requirement: "PromoÃ§Ã£o e divulgaÃ§Ã£o de material educativo.",
      requiredDocs: "PublicaÃ§Ã£o, pelo municÃ­pio, de material publicitÃ¡rio educativo em meio impresso ou realizaÃ§Ã£o de campanha de mÃ­dia digital multiplataforma (cÃ³pia da publicaÃ§Ã£o + comprovaÃ§Ã£o de contrataÃ§Ã£o do serviÃ§o ou de impulsionamento em mÃ­dia digital).",
      maxPoints: 4,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 1, maxPoints: 4 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 12,
    },
    {
      id: "B.6",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "AÃ§Ãµes de educaÃ§Ã£o ambiental escolar (com projeto)",
      requirement: "AÃ§Ãµes de educaÃ§Ã£o ambiental em Ã¢mbito escolar.",
      requiredDocs: "Projeto Escolar/Educacional (sucinto, conforme RelatÃ³rio TÃ©cnico, contendo problemÃ¡tica, justificativa, objetivos, culminÃ¢ncia, metodologia, cronograma e avaliaÃ§Ã£o) + ExecuÃ§Ã£o comprovada atravÃ©s de RelatÃ³rio Operacional.",
      maxPoints: 12,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 13,
    },
    {
      id: "B.7",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Eventos pÃºblicos temÃ¡ticos de educaÃ§Ã£o ambiental",
      requirement: "Atividades sociais de educaÃ§Ã£o ambiental.",
      requiredDocs: "RelatÃ³rio Operacional (com registro fotogrÃ¡fico datado, local de realizaÃ§Ã£o, pÃºblico-alvo, lista de frequÃªncia, conteÃºdos abordados, relato sucinto, material divulgado) de eventos pÃºblicos temÃ¡ticos.",
      maxPoints: 8,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 14,
    },
    {
      id: "B.8",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Programa GuardiÃµes Ambientais Mirins ou Brigadistas Mirins",
      requirement: "ImplementaÃ§Ã£o do Programa 'GuardiÃµes Ambientais Mirins' ou 'Brigadistas Mirins': Programa de protagonismo estudantil, implementado em ao menos 01 escola da rede municipal em zona urbana + 01 em zona rural.",
      requiredDocs: "Projeto PedagÃ³gico Simplificado + RelaÃ§Ã£o dos Alunos Participantes + RelatÃ³rio FotogrÃ¡fico Comentado (georreferenciado e datado).",
      maxPoints: 14,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 15,
    },
    {
      id: "B.9",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Congresso Municipal de Meio Ambiente (mÃ­nimo 2 dias)",
      requirement: "RealizaÃ§Ã£o do Congresso Municipal de Meio Ambiente: Evento (congresso, seminÃ¡rio ou fÃ³rum) aberto Ã  comunidade, com duraÃ§Ã£o mÃ­nima de 02 dias, para debater a pauta ambiental local.",
      requiredDocs: "Material de DivulgaÃ§Ã£o + ProgramaÃ§Ã£o Oficial + Lista de PresenÃ§a + Ata ou RelatÃ³rio Final do Evento + Registro FotogrÃ¡fico (georreferenciado).",
      maxPoints: 14,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 16,
    },
    {
      id: "B.10",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "Campanha de combate Ã  caÃ§a ilegal",
      requirement: "Campanha Educativa de Combate Ã  CaÃ§a Ilegal: Conjunto de aÃ§Ãµes voltadas Ã  conscientizaÃ§Ã£o da populaÃ§Ã£o, especialmente na zona rural.",
      requiredDocs: "Plano de AÃ§Ã£o Simplificado + CÃ³pia do Material Educativo Produzido + RelatÃ³rio FotogrÃ¡fico de ao menos 02 aÃ§Ãµes de sensibilizaÃ§Ã£o em locais diferentes (georreferenciadas).",
      maxPoints: 8,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 17,
    },
    {
      id: "B.11",
      axis: "B",
      axisName: "EducaÃ§Ã£o Ambiental",
      axisMinPoints: 50,
      description: "PÃ¡gina em rede social exclusiva de meio ambiente (mÃ­n. 4 posts/mÃªs por 12 meses)",
      requirement: "ManutenÃ§Ã£o de PÃ¡gina Ativa em Rede Social sobre Meio Ambiente: pÃ¡gina ou perfil em rede social de acesso pÃºblico, exclusivamente dedicada Ã  divulgaÃ§Ã£o de informaÃ§Ãµes e aÃ§Ãµes de educaÃ§Ã£o ambiental.",
      requiredDocs: "IdentificaÃ§Ã£o da PÃ¡gina (link de acesso pÃºblico + print) + RelatÃ³rio de Atividade Continuada (mÃ­nimo 04 publicaÃ§Ãµes mensais durante pelo menos 12 meses do perÃ­odo de apuraÃ§Ã£o).",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 18,
    },

    // â”€â”€ C â€” ReduÃ§Ã£o do Desmatamento â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "C.1",
      axis: "C",
      axisName: "ReduÃ§Ã£o do Desmatamento e RecuperaÃ§Ã£o de Ãreas Degradadas",
      axisMinPoints: 50,
      description: "ReduÃ§Ã£o do desmatamento (anÃ¡lise tÃ©cnica SEMARH + link de mapas)",
      requirement: "ReduÃ§Ã£o do desmatamento.",
      requiredDocs: "O municÃ­pio deverÃ¡ postular o presente item, requerendo a anÃ¡lise e a emissÃ£o do RelatÃ³rio TÃ©cnico referente ao Ãndice de ReduÃ§Ã£o de Desmatamento Ilegal, conforme metodologia descrita no Termo de ReferÃªncia vigente.",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: true,                   // âœ… campo especial â€” exige link de mapas
      isReusable: false,
      validYears: null,
      order: 19,
    },
    {
      id: "C.2",
      axis: "C",
      axisName: "ReduÃ§Ã£o do Desmatamento e RecuperaÃ§Ã£o de Ãreas Degradadas",
      axisMinPoints: 50,
      description: "IdentificaÃ§Ã£o de Ã¡reas degradadas e monitoramento (2 anos)",
      requirement: "IdentificaÃ§Ã£o de Ã¡reas degradadas e seu monitoramento (2 anos).",
      requiredDocs: "RelatÃ³rio Operacional (com identificaÃ§Ã£o das Ã¡reas, coordenadas geogrÃ¡ficas, diagnÃ³stico do solo, da Ã¡gua e da vegetaÃ§Ã£o, fatores que resultaram na degradaÃ§Ã£o, registro fotogrÃ¡fico datado e georreferenciado, e anÃ¡lise da evoluÃ§Ã£o da degradaÃ§Ã£o) + Mapa georreferenciado + Quadro resumo de Ã¡reas degradadas + Assinatura de responsÃ¡vel tÃ©cnico habilitado.",
      maxPoints: 10,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 10 },
      hasMapLink: false,
      isReusable: false,
      validYears: 3,                      // âœ… vÃ¡lido por atÃ© 3 anos (art. 16 Â§3Âº)
      order: 20,
    },
    {
      id: "C.3",
      axis: "C",
      axisName: "ReduÃ§Ã£o do Desmatamento e RecuperaÃ§Ã£o de Ãreas Degradadas",
      axisMinPoints: 50,
      description: "RecuperaÃ§Ã£o e/ou monitoramento de Ã¡reas degradadas",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de recuperaÃ§Ã£o e/ou monitoramento (por dois anos) de Ã¡reas degradadas identificadas no item C.2.",
      requiredDocs: "Projeto tÃ©cnico de ExecuÃ§Ã£o e Monitoramento vinculado Ã s Ã¡reas identificadas no Item C.2 + RelatÃ³rio Operacional (com ART) + RelatÃ³rio TÃ©cnico de Monitoramento.",
      maxPoints: 24,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 6, maxPoints: 24 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 21,
    },
    {
      id: "C.4",
      axis: "C",
      axisName: "ReduÃ§Ã£o do Desmatamento e RecuperaÃ§Ã£o de Ãreas Degradadas",
      axisMinPoints: 50,
      description: "CriaÃ§Ã£o e manutenÃ§Ã£o de Viveiro Municipal",
      requirement: "CriaÃ§Ã£o e ManutenÃ§Ã£o de Viveiro Municipal.",
      requiredDocs: "CÃ³pia da Lei ou Decreto Municipal de criaÃ§Ã£o + Notas fiscais de insumos + RelatÃ³rio fotogrÃ¡fico (mÃ­nimo 5 fotos georreferenciadas) + InventÃ¡rio de mudas assinado por responsÃ¡vel tÃ©cnico + RelatÃ³rio de plantio das mudas.",
      maxPoints: 16,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 22,
    },
    {
      id: "C.5",
      axis: "C",
      axisName: "ReduÃ§Ã£o do Desmatamento e RecuperaÃ§Ã£o de Ãreas Degradadas",
      axisMinPoints: 50,
      description: "Plantio anual de mudas nativas (por faixa populacional)",
      requirement: "Plantio anual de mudas de espÃ©cies nativas em quantidade relativa Ã  populaÃ§Ã£o do municÃ­pio, vedada a contagem de plantio em outros itens.",
      requiredDocs: "Projeto TÃ©cnico assinado por responsÃ¡vel habilitado (com ART) + RelatÃ³rio Operacional + Mapa georreferenciado com distribuiÃ§Ã£o dos pontos de plantio.",
      maxPoints: 30,
      scoringType: "per_faixa" as const,
      scoringConfig: {
        type: "population",
        faixas: [
          { minPop: 0,      maxPop: 3000,   levels: [{ level: 1, minQty: 250,  points: 8 }, { level: 2, minQty: 500,  points: 12 }, { level: 3, minQty: 900,  points: 30 }] },
          { minPop: 3001,   maxPop: 5000,   levels: [{ level: 1, minQty: 350,  points: 8 }, { level: 2, minQty: 650,  points: 12 }, { level: 3, minQty: 1100, points: 30 }] },
          { minPop: 5001,   maxPop: 10000,  levels: [{ level: 1, minQty: 500,  points: 8 }, { level: 2, minQty: 900,  points: 12 }, { level: 3, minQty: 1500, points: 30 }] },
          { minPop: 10001,  maxPop: 30000,  levels: [{ level: 1, minQty: 650,  points: 8 }, { level: 2, minQty: 1300, points: 12 }, { level: 3, minQty: 2000, points: 30 }] },
          { minPop: 30001,  maxPop: 60000,  levels: [{ level: 1, minQty: 900,  points: 8 }, { level: 2, minQty: 1800, points: 12 }, { level: 3, minQty: 3000, points: 30 }] },
          { minPop: 60001,  maxPop: 100000, levels: [{ level: 1, minQty: 1300, points: 8 }, { level: 2, minQty: 2500, points: 12 }, { level: 3, minQty: 4500, points: 30 }] },
          { minPop: 100001, maxPop: 300000, levels: [{ level: 1, minQty: 1800, points: 8 }, { level: 2, minQty: 2800, points: 12 }, { level: 3, minQty: 4500, points: 30 }] },
          { minPop: 300001, maxPop: null,   levels: [{ level: 1, minQty: 2200, points: 8 }, { level: 2, minQty: 3800, points: 12 }, { level: 3, minQty: 6000, points: 30 }] },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 23,
    },

    // â”€â”€ D â€” Queimadas, Solo e Biodiversidade â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "D.1",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Brigada pÃºblica municipal de combate a incÃªndios florestais",
      requirement: "ExistÃªncia de brigada pÃºblica municipal de combate a incÃªndios florestais.",
      requiredDocs: "Instrumento legal de criaÃ§Ã£o da brigada + RelatÃ³rio Operacional (endereÃ§o e descriÃ§Ã£o da sede fÃ­sica com fotos datadas e georreferenciadas + instrumento legal de nomeaÃ§Ã£o dos componentes + vÃ­nculo municipal com Chefe da Brigada + treinamento comprovado + relaÃ§Ã£o de EPIs e materiais + relatÃ³rio de atividades preventivas e de combate).",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 24,
    },
    {
      id: "D.2",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Plano Municipal de MudanÃ§as ClimÃ¡ticas (PMMC)",
      requirement: "Plano Municipal de MudanÃ§as ClimÃ¡ticas (PMMC).",
      requiredDocs: "Instrumento legal de aprovaÃ§Ã£o e publicaÃ§Ã£o do PMMC no DiÃ¡rio Oficial + CÃ³pia integral do PMMC, contemplando estratÃ©gias e metas de mitigaÃ§Ã£o e adaptaÃ§Ã£o + DefiniÃ§Ã£o de responsabilidades e cronograma de execuÃ§Ã£o.",
      maxPoints: 13,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 25,
    },
    {
      id: "D.3",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Plano de PrevenÃ§Ã£o e Combate a IncÃªndios Florestais (PPCIF)",
      requirement: "Plano de PrevenÃ§Ã£o e Combate a IncÃªndios Florestais e Queimadas.",
      requiredDocs: "Instrumento legal de aprovaÃ§Ã£o e publicaÃ§Ã£o do PPCIF no DiÃ¡rio Oficial + Plano completo com abrangÃªncia municipal (diagnÃ³stico, estrutura de governanÃ§a, protocolos operacionais, inventÃ¡rio de recursos, plano de prevenÃ§Ã£o, de capacitaÃ§Ã£o, de resposta e cronograma anual).",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 26,
    },
    {
      id: "D.4",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "GovernanÃ§a Municipal para Agenda 2030/ODS",
      requirement: "InstitucionalizaÃ§Ã£o da GovernanÃ§a Municipal para a Agenda 2030 (ODS).",
      requiredDocs: "Carta-Compromisso 'Meu MunicÃ­pio pelos ODS 2025-2030' + Lei ou Decreto de criaÃ§Ã£o da ComissÃ£o Municipal para os ODS + Portaria de NomeaÃ§Ã£o dos Membros + Regimento Interno publicado em DiÃ¡rio Oficial + Plano de AÃ§Ã£o e DiagnÃ³stico Situacional.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 27,
    },
    {
      id: "D.5",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "AÃ§Ãµes de proteÃ§Ã£o de solo",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de ProteÃ§Ã£o de Solo.",
      requiredDocs: "RelatÃ³rio Operacional contendo diagnÃ³stico da Ã¡rea, metodologia completa, tÃ©cnicas e materiais empregados (cobertura, contenÃ§Ã£o, plantio direto, cercamento etc.) + ART + registros fotogrÃ¡ficos georreferenciados antes, durante e depois.",
      maxPoints: 16,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 28,
    },
    {
      id: "D.6",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "InventÃ¡rio faunÃ­stico e monitoramento de espÃ©cies silvestres",
      requirement: "IdentificaÃ§Ã£o e monitoramento de espÃ©cies da fauna silvestre no MunicÃ­pio.",
      requiredDocs: "InventÃ¡rio faunÃ­stico com amostragem sazonal + RelatÃ³rio de Monitoramento, AtualizaÃ§Ã£o e Defesa das EspÃ©cies Silvestres + ART.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 29,
    },
    {
      id: "D.7",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Bem-estar animal (abrigo, castraÃ§Ã£o, atendimento veterinÃ¡rio)",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de promoÃ§Ã£o do bem-estar animal.",
      requiredDocs: "RelatÃ³rio com descriÃ§Ã£o da estrutura fÃ­sica/quantitativo de animais (abrigo); e/ou relatÃ³rio com quantitativo de animais atendidos em procedimentos de castraÃ§Ã£o; e/ou relatÃ³rio de atendimento mÃ©dico veterinÃ¡rio gratuito.",
      maxPoints: 12,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 30,
    },
    {
      id: "D.8",
      axis: "D",
      axisName: "ReduÃ§Ã£o do Risco de Queimadas, ConservaÃ§Ã£o do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "CoordenaÃ§Ã£o Municipal de Defesa Civil (CMDC)",
      requirement: "EstruturaÃ§Ã£o da CoordenaÃ§Ã£o Municipal de Defesa Civil (CMDC).",
      requiredDocs: "Lei ou Decreto de criaÃ§Ã£o e regulamentaÃ§Ã£o da CMDC + Plano Municipal de AÃ§Ã£o da Defesa Civil publicado + Ato de nomeaÃ§Ã£o do Coordenador Municipal + Ato de nomeaÃ§Ã£o dos TÃ©cnicos Operacionais + RelatÃ³rio Operacional de atividades.",
      maxPoints: 13,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 31,
    },

    // â”€â”€ E â€” ProteÃ§Ã£o de Mananciais â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "E.1",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "Cobertura de esgotamento sanitÃ¡rio (% Ã— 0,15)",
      requirement: "Cobertura da rede de esgotamento sanitÃ¡rio.",
      requiredDocs: "DeclaraÃ§Ã£o emitida pela concessionÃ¡ria ou empresa de serviÃ§os de saneamento + LicenÃ§a ambiental de OperaÃ§Ã£o do Ã³rgÃ£o competente, em validade.",
      maxPoints: 12,
      scoringType: "percentage" as const,
      scoringConfig: { type: "percentage", coefficient: 0.15, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 32,
    },
    {
      id: "E.2",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "AÃ§Ãµes de proteÃ§Ã£o de nascentes",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de proteÃ§Ã£o de nascentes.",
      requiredDocs: "Projeto TÃ©cnico (com ART), contendo diagnÃ³stico da Ã¡rea + RelatÃ³rio Operacional (com ART) com localizaÃ§Ã£o das Ã¡reas, mapas e coordenadas + ComprovaÃ§Ã£o documental de insumos + Mapas georreferenciados das Ã¡reas protegidas.",
      maxPoints: 16,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 33,
    },
    {
      id: "E.3",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "ProteÃ§Ã£o de Ã¡guas subterrÃ¢neas",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de proteÃ§Ã£o e de recursos hÃ­dricos (Ã¡guas subterrÃ¢neas).",
      requiredDocs: "RelatÃ³rio operacional contendo diagnÃ³stico, descriÃ§Ã£o e geolocalizaÃ§Ã£o da fonte + DescriÃ§Ã£o da aÃ§Ã£o de proteÃ§Ã£o proposta + metodologia + demonstraÃ§Ã£o de resultados obtidos (com registro fotogrÃ¡fico datado e georreferenciado) + responsabilidade tÃ©cnica.",
      maxPoints: 16,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 34,
    },
    {
      id: "E.4",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "ProteÃ§Ã£o e manutenÃ§Ã£o de Ã¡guas superficiais",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes de proteÃ§Ã£o e/ou manutenÃ§Ã£o de recursos hÃ­dricos (Ã¡guas superficiais).",
      requiredDocs: "Projeto TÃ©cnico (com ART) + RelatÃ³rio Operacional (com ART), contendo localizaÃ§Ã£o e diagnÃ³stico das Ã¡reas com mapas, coordenadas e extensÃ£o + ComprovaÃ§Ã£o documental de insumos e mudas + Mapas georreferenciados das Ã¡reas protegidas.",
      maxPoints: 16,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 35,
    },
    {
      id: "E.5",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "Monitoramento da qualidade da Ã¡gua (poÃ§os municipais)",
      requirement: "Monitoramento da qualidade da Ã¡gua de mananciais subterrÃ¢neos de abastecimento pÃºblico.",
      requiredDocs: "RelatÃ³rio TÃ©cnico de Monitoramento, assinado por responsÃ¡vel habilitado, contendo laudos laboratoriais de anÃ¡lise da Ã¡gua (fÃ­sico-quÃ­mica e bacteriolÃ³gica) dos poÃ§os municipais, cobrindo no mÃ­nimo 2 trimestres distintos do ano de apuraÃ§Ã£o + IdentificaÃ§Ã£o dos pontos de coleta georreferenciados.",
      maxPoints: 15,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 5, maxPoints: 15 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 36,
    },
    {
      id: "E.6",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "RegularizaÃ§Ã£o e outorga de captaÃ§Ã£o subterrÃ¢nea",
      requirement: "RegularizaÃ§Ã£o e eficiÃªncia na gestÃ£o de captaÃ§Ã£o subterrÃ¢nea.",
      requiredDocs: "CÃ³pia da Portaria de Outorga de Direito de Uso (ou Dispensa de Outorga) emitida pelo Ã³rgÃ£o competente para os poÃ§os de domÃ­nio municipal vigentes no ano de apuraÃ§Ã£o, conforme inventÃ¡rio do item E.7.",
      maxPoints: 13,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 37,
    },
    {
      id: "E.7",
      axis: "E",
      axisName: "ProteÃ§Ã£o de Mananciais de Abastecimento PÃºblico",
      axisMinPoints: 50,
      description: "Cadastro tÃ©cnico municipal de poÃ§os e fontes",
      requirement: "Cadastro TÃ©cnico Municipal de PoÃ§os e Fontes.",
      requiredDocs: "InventÃ¡rio HidrogeolÃ³gico Municipal, apresentado em formato de mapa georreferenciado e planilha tÃ©cnica, contendo a localizaÃ§Ã£o de todos os pontos de captaÃ§Ã£o de domÃ­nio municipal, com dados de vazÃ£o, profundidade e status de operaÃ§Ã£o.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 38,
    },

    // â”€â”€ F â€” Controle da PoluiÃ§Ã£o â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "F.1",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate Ã  poluiÃ§Ã£o sonora",
      requirement: "Campanhas educativas ou de combate e controle da poluiÃ§Ã£o sonora.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades, locais de realizaÃ§Ã£o, registro fotogrÃ¡fico datado e perÃ­odo de realizaÃ§Ã£o mÃ­nimo de 4 dias de campanha, distribuÃ­dos em 2 semestres do ano de apuraÃ§Ã£o.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 39,
    },
    {
      id: "F.2",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate Ã  poluiÃ§Ã£o atmosfÃ©rica",
      requirement: "Campanhas educativas ou de combate da poluiÃ§Ã£o atmosfÃ©rica e mudanÃ§as climÃ¡ticas.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades, locais de realizaÃ§Ã£o, registro fotogrÃ¡fico datado e perÃ­odo de realizaÃ§Ã£o mÃ­nimo de 4 dias de campanha, distribuÃ­dos em 2 semestres do ano de apuraÃ§Ã£o.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 40,
    },
    {
      id: "F.3",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate Ã  poluiÃ§Ã£o visual",
      requirement: "Campanhas educativas ou de combate e controle da poluiÃ§Ã£o visual.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades, locais de realizaÃ§Ã£o, registro fotogrÃ¡fico datado e perÃ­odo de realizaÃ§Ã£o mÃ­nimo de 4 dias de campanha, distribuÃ­dos em 2 semestres do ano de apuraÃ§Ã£o.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 41,
    },
    {
      id: "F.4",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "EstruturaÃ§Ã£o da fiscalizaÃ§Ã£o ambiental municipal",
      requirement: "Planejamento e estruturaÃ§Ã£o da fiscalizaÃ§Ã£o ambiental municipal.",
      requiredDocs: "RelatÃ³rio Operacional descrevendo quadro de funcionÃ¡rios de fiscalizaÃ§Ã£o (conforme Lei Federal n. 9.605/98, art. 70, Â§1Âº), com comprovaÃ§Ã£o de vÃ­nculo + comprovante de designaÃ§Ã£o da autoridade julgadora + planejamento de atividades de fiscalizaÃ§Ã£o preventiva.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 42,
    },
    {
      id: "F.5",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "FiscalizaÃ§Ã£o de poluiÃ§Ã£o sonora (â‰¥6 dias/ano, 3 quadrimestres)",
      requirement: "ExercÃ­cio da fiscalizaÃ§Ã£o de fontes de poluiÃ§Ã£o sonora.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades de fiscalizaÃ§Ã£o relacionadas Ã  poluiÃ§Ã£o sonora em pelo menos 06 dias distintos no perÃ­odo de apuraÃ§Ã£o, distribuÃ­dos em pelo menos 3 quadrimestres distintos, com fotos datadas e georreferenciadas.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 43,
    },
    {
      id: "F.6",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "FiscalizaÃ§Ã£o de poluiÃ§Ã£o visual (â‰¥6 dias/ano, 3 quadrimestres)",
      requirement: "ExercÃ­cio da fiscalizaÃ§Ã£o de fontes de poluiÃ§Ã£o visual.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades de fiscalizaÃ§Ã£o relacionadas Ã  poluiÃ§Ã£o visual em pelo menos 06 dias distintos no perÃ­odo de apuraÃ§Ã£o, distribuÃ­dos em pelo menos 3 quadrimestres distintos, com fotos e descriÃ§Ã£o de processos de apuraÃ§Ã£o de irregularidades.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 44,
    },
    {
      id: "F.7",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "FiscalizaÃ§Ã£o de poluiÃ§Ã£o atmosfÃ©rica (â‰¥6 dias/ano, 3 quadrimestres)",
      requirement: "ExercÃ­cio da fiscalizaÃ§Ã£o de fontes de poluiÃ§Ã£o atmosfÃ©rica.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades de fiscalizaÃ§Ã£o relacionadas Ã  poluiÃ§Ã£o atmosfÃ©rica em pelo menos 06 dias distintos no perÃ­odo de apuraÃ§Ã£o, distribuÃ­dos em pelo menos 3 quadrimestres distintos, contendo fotos e descriÃ§Ã£o de processos de apuraÃ§Ã£o de irregularidades.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 45,
    },
    {
      id: "F.8",
      axis: "F",
      axisName: "Controle da PoluiÃ§Ã£o e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "CertidÃ£o Negativa de DÃ©bitos Ambientais (SEMARH)",
      requirement: "ComprovaÃ§Ã£o de Regularidade Ambiental Municipal.",
      requiredDocs: "ApresentaÃ§Ã£o de CertidÃ£o Negativa de DÃ©bitos Ambientais, emitida pelo Ã³rgÃ£o ambiental competente (SEMARH), vÃ¡lida dentro do perÃ­odo de apuraÃ§Ã£o do certame.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 46,
    },

    // â”€â”€ G â€” EdificaÃ§Ãµes Irregulares â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "G.1",
      axis: "G",
      axisName: "EdificaÃ§Ãµes Irregulares",
      axisMinPoints: 50,
      description: "Estrutura institucional de controle de uso do solo",
      requirement: "Estrutura institucional de controle da aplicaÃ§Ã£o da lei municipal de uso e ocupaÃ§Ã£o do solo.",
      requiredDocs: "Instrumento legal de instituiÃ§Ã£o da polÃ­tica municipal de uso e ocupaÃ§Ã£o do solo + instrumento legal de instituiÃ§Ã£o do Ã³rgÃ£o designado para o controle + instrumento legal de nomeaÃ§Ã£o do quadro funcional + instrumento legal de criaÃ§Ã£o do conselho municipal de desenvolvimento urbano.",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 47,
    },
    {
      id: "G.2",
      axis: "G",
      axisName: "EdificaÃ§Ãµes Irregulares",
      axisMinPoints: 50,
      description: "Controle efetivo de uso do solo (licenÃ§as urbanÃ­sticas)",
      requirement: "Controle efetivo de uso e ocupaÃ§Ã£o do solo do municÃ­pio (quando possuir lei municipal de uso e ocupaÃ§Ã£o do solo).",
      requiredDocs: "RelatÃ³rio operacional (detalhamento das licenÃ§as urbanÃ­sticas emitidas no perÃ­odo de apuraÃ§Ã£o: nÃºmero da licenÃ§a, interessado e data de validade).",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 48,
    },
    {
      id: "G.3",
      axis: "G",
      axisName: "EdificaÃ§Ãµes Irregulares",
      axisMinPoints: 50,
      description: "FiscalizaÃ§Ã£o de irregularidades no uso do solo (â‰¥6 dias/3 quadrimestres)",
      requirement: "ExercÃ­cio de fiscalizaÃ§Ã£o de irregularidades na aplicaÃ§Ã£o da norma de uso e ocupaÃ§Ã£o do solo.",
      requiredDocs: "RelatÃ³rio Operacional contendo a descriÃ§Ã£o das atividades de fiscalizaÃ§Ã£o relacionadas Ã  inadequaÃ§Ã£o da norma de uso e ocupaÃ§Ã£o do solo, em pelo menos 06 dias distintos, distribuÃ­dos em pelo menos 3 quadrimestres distintos.",
      maxPoints: 25,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 49,
    },
    {
      id: "G.4",
      axis: "G",
      axisName: "EdificaÃ§Ãµes Irregulares",
      axisMinPoints: 50,
      description: "Proposta de requalificaÃ§Ã£o urbana em execuÃ§Ã£o",
      requirement: "Proposta de requalificaÃ§Ã£o urbana em execuÃ§Ã£o durante o perÃ­odo de apuraÃ§Ã£o.",
      requiredDocs: "CÃ³pia do plano de requalificaÃ§Ã£o urbana + relatÃ³rio operacional + comprovaÃ§Ã£o de responsabilidade tÃ©cnica.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 50,
    },
    {
      id: "G.5",
      axis: "G",
      axisName: "EdificaÃ§Ãµes Irregulares",
      axisMinPoints: 50,
      description: "Mapeamento atualizado de assentamentos precÃ¡rios",
      requirement: "Mapeamento atualizado de assentamentos precÃ¡rios e edificaÃ§Ãµes irregulares.",
      requiredDocs: "DiagnÃ³stico do territÃ³rio municipal, no perÃ­odo de apuraÃ§Ã£o, considerando variÃ¡veis de edificaÃ§Ãµes irregulares e assentamentos precÃ¡rios (renda domiciliar, situaÃ§Ã£o fundiÃ¡ria, domÃ­nio da Ã¡rea, populaÃ§Ã£o, infraestrutura urbana, padrÃ£o viÃ¡rio, padrÃ£o de lotes, Ã¡reas de risco, etc.).",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 51,
    },

    // â”€â”€ H â€” Unidades de ConservaÃ§Ã£o â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "H.1",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "IncidÃªncia de UC federal/estadual no territÃ³rio",
      requirement: "IncidÃªncia territorial de Unidade de ConservaÃ§Ã£o instituÃ­da por outro ente da federaÃ§Ã£o (federal/estadual).",
      requiredDocs: "Ato normativo de criaÃ§Ã£o, conforme legislaÃ§Ã£o federal e/ou estadual + relatÃ³rio apresentando comprovaÃ§Ã£o de incidÃªncia territorial.",
      maxPoints: 20,
      scoringType: "per_faixa" as const,
      scoringConfig: {
        type: "territory",
        ranges: [
          { minPct: 0,  maxPct: 25,   points: 5  },
          { minPct: 25, maxPct: 50,   points: 10 },
          { minPct: 50, maxPct: 75,   points: 15 },
          { minPct: 75, maxPct: null, points: 20 },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 52,
    },
    {
      id: "H.2",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "AÃ§Ãµes conjuntas com UC estadual/federal",
      requirement: "ExecuÃ§Ã£o de aÃ§Ãµes conjuntas com as Unidades de ConservaÃ§Ã£o Estadual e/ou Federal quando impossÃ­vel criar Unidades de ConservaÃ§Ã£o Municipal.",
      requiredDocs: "RelatÃ³rio tÃ©cnico com descriÃ§Ã£o da aÃ§Ã£o de cooperaÃ§Ã£o para gestÃ£o da UC + apresentaÃ§Ã£o de metodologia + demonstraÃ§Ã£o de resultados obtidos (com registro fotogrÃ¡fico datado e georreferenciado).",
      maxPoints: 60,
      scoringType: "per_unit" as const,
      scoringConfig: { type: "per_unit", unitValue: 10, maxPoints: 60 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 53,
    },
    {
      id: "H.3",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "UC municipal no territÃ³rio",
      requirement: "IncidÃªncia territorial de unidade de conservaÃ§Ã£o (municipal).",
      requiredDocs: "Ato normativo de criaÃ§Ã£o, observado os parÃ¢metros da legislaÃ§Ã£o federal e estadual + relatÃ³rio apresentando comprovaÃ§Ã£o de incidÃªncia territorial.",
      maxPoints: 45,
      scoringType: "per_faixa" as const,
      scoringConfig: {
        type: "territory",
        ranges: [
          { minPct: 0,  maxPct: 25,   points: 30 },
          { minPct: 25, maxPct: 50,   points: 35 },
          { minPct: 50, maxPct: 75,   points: 40 },
          { minPct: 75, maxPct: null, points: 45 },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 54,
    },
    {
      id: "H.4",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "Sede administrativa de UC municipal",
      requirement: "Estrutura fÃ­sica de unidade de conservaÃ§Ã£o municipal: existÃªncia de sede administrativa.",
      requiredDocs: "RelatÃ³rio operacional com descriÃ§Ã£o dos equipamentos e instalaÃ§Ãµes localizadas na unidade de conservaÃ§Ã£o municipal, com registro fotogrÃ¡fico datado.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 55,
    },
    {
      id: "H.5",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "Plano de manejo de UC municipal",
      requirement: "InstituiÃ§Ã£o de plano de manejo da unidade de conservaÃ§Ã£o municipal.",
      requiredDocs: "CÃ³pia do plano de manejo da unidade de conservaÃ§Ã£o municipal aprovado pela SEMARH + publicaÃ§Ã£o do ato de aprovaÃ§Ã£o + relatÃ³rio operacional de execuÃ§Ã£o do plano de manejo, com registro fotogrÃ¡fico datado.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 56,
    },
    {
      id: "H.6",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "Conselho gestor de UC municipal",
      requirement: "ExistÃªncia do conselho gestor da unidade de conservaÃ§Ã£o municipal.",
      requiredDocs: "Ato legal de criaÃ§Ã£o do conselho conforme Â§6Âº, art. 17 do Decreto Federal nÂº 4.340/2002 + instrumento legal de nomeaÃ§Ã£o dos membros do conselho + atas das reuniÃµes do conselho.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 57,
    },
    {
      id: "H.7",
      axis: "H",
      axisName: "Unidades de ConservaÃ§Ã£o",
      axisMinPoints: 50,
      description: "UC completa com estrutura (H.3+H.4+H.5+H.6) â€” bÃ´nus",
      requirement: "CriaÃ§Ã£o de Unidade de conservaÃ§Ã£o com estrutura completa abrangendo os itens H.3 a H.6.",
      requiredDocs: "Todos os documentos comprobatÃ³rios dos itens H.3 a H.6.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 58,
    },

    // â”€â”€ I â€” LegislaÃ§Ã£o Ambiental â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      id: "I.1",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "PolÃ­tica Municipal de Combate Ã s MudanÃ§as ClimÃ¡ticas",
      requirement: "PolÃ­tica Municipal de Combate Ã s MudanÃ§as ClimÃ¡ticas.",
      requiredDocs: "LegislaÃ§Ã£o ambiental municipal sobre o tema, descrevendo aÃ§Ãµes ambientais, com objetivos a serem perseguidos, devidamente publicada.",
      maxPoints: 8,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 59,
    },
    {
      id: "I.2",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "CobranÃ§a por coleta de resÃ­duos (taxa municipal)",
      requirement: "InstituiÃ§Ã£o de cobranÃ§a por serviÃ§o de coleta, remoÃ§Ã£o e destinaÃ§Ã£o de resÃ­duos sÃ³lidos e sua respectiva cobranÃ§a.",
      requiredDocs: "LegislaÃ§Ã£o municipal sobre o tema, conforme o art. 29, inciso II, da Lei Federal nÂº 11.445/2007 + Documento oficial apto a comprovar as receitas decorrentes da cobranÃ§a da Taxa.",
      maxPoints: 20,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 60,
    },
    {
      id: "I.3",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "PolÃ­tica Municipal de Meio Ambiente",
      requirement: "PolÃ­tica Municipal de Meio Ambiente.",
      requiredDocs: "LegislaÃ§Ã£o ambiental municipal sobre o tema, descrevendo aÃ§Ãµes ambientais, com objetivos a serem perseguidos, devidamente publicada.",
      maxPoints: 10,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 61,
    },
    {
      id: "I.4",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "PolÃ­tica Municipal de EducaÃ§Ã£o Ambiental",
      requirement: "PolÃ­tica Municipal de EducaÃ§Ã£o Ambiental.",
      requiredDocs: "LegislaÃ§Ã£o ambiental municipal sobre o tema, devidamente publicada.",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 62,
    },
    {
      id: "I.5",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Ã“rgÃ£o Municipal habilitado para licenciamento ambiental",
      requirement: "Ã“rgÃ£o Municipal de Meio Ambiente Habilitado para o Licenciamento.",
      requiredDocs: "CÃ³pia da Lei de CriaÃ§Ã£o do Ã“rgÃ£o Executivo Municipal + cÃ³pia do Ato ou Decreto de nomeaÃ§Ã£o do SecretÃ¡rio e TÃ©cnicos do Ã“rgÃ£o Municipal de Meio Ambiente com formaÃ§Ã£o compatÃ­vel + DeclaraÃ§Ã£o Emitida Pela SEMARH que comprove a municipalizaÃ§Ã£o do licenciamento + RelatÃ³rio Operacional contendo todas as licenÃ§as expedidas no ano de apuraÃ§Ã£o.",
      maxPoints: 12,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
      order: 63,
    },
    {
      id: "I.6",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Fundo Municipal do Meio Ambiente",
      requirement: "Fundo Municipal do Meio Ambiente.",
      requiredDocs: "CÃ³pia da Lei de CriaÃ§Ã£o do Fundo Municipal do Meio Ambiente + cÃ³pia do decreto de regulamentaÃ§Ã£o + cÃ³pia das atas das reuniÃµes + cÃ³pia do Termo de posse dos conselheiros do Conselho Gestor do Fundo.",
      maxPoints: 5,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 64,
    },
    {
      id: "I.7",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o sonora",
      requirement: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o sonora.",
      requiredDocs: "CÃ³pia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 65,
    },
    {
      id: "I.8",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o visual",
      requirement: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o visual.",
      requiredDocs: "CÃ³pia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 66,
    },
    {
      id: "I.9",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o atmosfÃ©rica",
      requirement: "LegislaÃ§Ã£o de controle da poluiÃ§Ã£o atmosfÃ©rica.",
      requiredDocs: "CÃ³pia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 67,
    },
    {
      id: "I.10",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "LegislaÃ§Ãµes especÃ­ficas sobre licenciamento ambiental municipal",
      requirement: "LegislaÃ§Ãµes especÃ­ficas sobre o licenciamento ambiental municipal.",
      requiredDocs: "CÃ³pia dos instrumentos legais devidamente publicados.",
      maxPoints: 15,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 68,
    },
    {
      id: "I.11",
      axis: "I",
      axisName: "LegislaÃ§Ã£o sobre a PolÃ­tica Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "LegislaÃ§Ã£o de promoÃ§Ã£o do bem-estar animal",
      requirement: "LegislaÃ§Ã£o de promoÃ§Ã£o do bem-estar animal.",
      requiredDocs: "CÃ³pia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: "fixed" as const,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
      order: 69,
    },
  ];

  // âœ… Upsert usando prisma.criteria (nome correto do model no schema)
  for (const criterion of criteria) {
    await prisma.criteria.upsert({
      where: { id: criterion.id },
      update: criterion,
      create: criterion,
    });
  }
  console.log(`âœ… ${criteria.length} critÃ©rios criados/atualizados`);

  console.log("\nðŸŽ‰ Seed concluÃ­do com sucesso!");
  console.log("â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€");
  console.log("Admin:", admin.email);
  console.log("Senha provisÃ³ria: Admin@2026!");
  console.log("â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€");
}

main()
  .catch((e) => {
    console.error("âŒ Erro no seed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
