// prisma/seed.ts
import { PrismaClient, Prisma, ScoringType } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Iniciando seed...");

  // ── Certame de teste 2026 ──────────────────────────────────────────────────

  const certame2026 = await prisma.certame.upsert({
    where: { year: 2026 },
    update: {},
    create: {
      year: 2026,
      periodoInicio: new Date("2025-01-01"),
      periodoFim: new Date("2026-12-31"),
      isActive: true,
      isClosed: false,
    },
  });
  console.log("✅ Certame 2026 criado:", certame2026.id);

  // ── Usuário admin padrão ───────────────────────────────────────────────────

  const passwordHash = await bcrypt.hash("Admin@2026!", 10);

  const admin = await prisma.user.upsert({
    where: { email: "eco@ambiental.com.br" },
    update: {},
    create: {
      email: "eco@ambiental.com.br",
      name: "Camila Loiola",
      passwordHash,
      role: "admin",
      mustChangePassword: true,
      isActive: true,
    },
  });
  console.log("✅ Admin criado:", admin.email);

  // ── Critérios do Decreto 24.288/2025 ──────────────────────────────────────

  const criteria: Prisma.CriteriaCreateInput[] = [
    // ── A — Gerenciamento de Resíduos Sólidos ─────────────────────────────────
    {
      id: "A.1",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Destinação final ambientalmente adequada de resíduos em aterro sanitário",
      requirement: "Destinação final ambientalmente adequada de resíduos em aterro sanitário, em funcionamento, de acordo com as normas técnicas.",
      requiredDocs: "Cópia da Licença de Operação (LO) do aterro sanitário receptor vigente durante todo o período de apuração + Cópia do Contrato ou instrumento de parceria vigente com o aterro sanitário ou com a empresa responsável pelo transporte e destinação final + Prova da Efetiva e Contínua Destinação: Manifestos de Transporte de Resíduos (MTR) ou Comprovação Fiscal do Serviço + Comprovante de cadastro do município no SINIR.",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "A.2",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Coleta seletiva com adequada destinação",
      requirement: "Possuir serviço regular de coleta seletiva e adequada destinação.",
      requiredDocs: "Instrumento de planejamento (projeto técnico ou programa) + Relatório Operacional contendo descrição das ações com registro fotográfico datado + Comprovação de destinação para cooperativas, comércios atacadistas dos resíduos coletados ou correlatos.",
      maxPoints: 14,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "A.3",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Coleta, transbordo e limpeza pública (varrição, capina e poda)",
      requirement: "Possuir serviço regular de coleta, transbordo e transporte de resíduos sólidos e de limpeza pública abrangendo varrição, capina e poda de árvores em vias e logradouros públicos.",
      requiredDocs: "Relatório Operacional do período de apuração, discriminando a execução de cada serviço, registro fotográfico com informações de data e georreferenciamento sobreposto a imagem.",
      maxPoints: 14,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "A.4",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Coleta e destinação de resíduos de saúde (RSS)",
      requirement: "Possuir serviço regular de coleta, transbordo e transporte de resíduos de serviço de saúde.",
      requiredDocs: "Licença Ambiental de Operação ou documento equivalente válidos da empresa contratada para a coleta e o transporte dos resíduos de serviço de saúde + Documento que comprove a destinação final ambientalmente adequada, tal como Manifesto de Transporte de Resíduos.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "A.5",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Plano Municipal de Gestão Integrada de Resíduos Sólidos",
      requirement: "Plano Municipal de Gestão Integrada de Resíduos Sólidos.",
      requiredDocs: "Apresentação do plano, ou plano simplificado (para municípios com menos de vinte mil habitantes) ou plano de saneamento básico conforme a Política Nacional de Resíduos Sólidos, inclusive atualização, com a respectiva publicação.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "A.6",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Pontos de entrega voluntária (PEVs) de recicláveis",
      requirement: "Possuir local de entrega voluntária de resíduos sólidos recicláveis, e comprovada destinação.",
      requiredDocs: "Relatório Operacional contendo a descrição dos pontos de entrega, endereço, descrição do quantitativo recebido e registros fotográficos de cada ponto de entrega + Comprovação de destinação para cooperativas ou comércios atacadistas dos resíduos coletados.",
      maxPoints: 12,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "A.7",
      axis: "A",
      axisName: "Gerenciamento de Resíduos Sólidos",
      axisMinPoints: 50,
      description: "Parceria com cooperativas de catadores",
      requirement: "Ações de incentivo e estímulo às cooperativas, associações e/ou outras modalidades de mobilização de trabalhadores de coleta e seleção de materiais recicláveis.",
      requiredDocs: "Contrato, convênio ou outro instrumento de parceria com entidade de direito privado que reúna trabalhadores de coleta e seleção de materiais recicláveis + projeto ou outro documento de planejamento + relatório operacional descrevendo as ações desenvolvidas.",
      maxPoints: 13,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── B — Educação Ambiental ─────────────────────────────────────────────────
    {
      id: "B.1",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Capacitação de recursos humanos municipais (dimensão ambiental)",
      requirement: "Capacitação de recursos humanos municipais sobre dimensão ambiental.",
      requiredDocs: "Relatório Operacional de cursos, palestras ou treinamentos (com fotos, ementa, data, carga horária, dados do educador e lista de frequência) voltados aos servidores do município. Somente será admitida a contagem de 3h por servidor.",
      maxPoints: 8,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.2",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Formação complementar de professores (dimensão ambiental)",
      requirement: "Formação complementar de professores voltada à dimensão ambiental.",
      requiredDocs: "Relatório Operacional de cursos, palestras e treinamentos (com fotos, ementa, data, carga horária, dados do instrutor e lista de frequência) voltados aos professores do município. Somente será admitida a contagem de 3h por servidor.",
      maxPoints: 8,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.3",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Treinamento de técnicos do órgão de meio ambiente",
      requirement: "Treinamento de técnicos e gestores do órgão local de meio ambiente.",
      requiredDocs: "Relatório Operacional de cursos, palestras e treinamentos (com fotos, ementa, data, carga horária, dados do instrutor e lista de frequência) voltados aos profissionais do órgão municipal de meio ambiente.",
      maxPoints: 10,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 10 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.4",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Estudos e pesquisas com ISSN/ISBN",
      requirement: "Desenvolvimento de estudos e pesquisas relacionados à dimensão ambiental.",
      requiredDocs: "Publicação, pelo município ou por ele financiado, de estudos por meio de artigos científicos, resumos, livros ou publicações científicas, com ISSN/ISBN.",
      maxPoints: 8,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.5",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Material educativo impresso ou campanha digital",
      requirement: "Promoção e divulgação de material educativo.",
      requiredDocs: "Publicação, pelo município, de material publicitário educativo em meio impresso ou realização de campanha de mídia digital multiplataforma (cópia da publicação + comprovação de contratação do serviço ou de impulsionamento em mídia digital).",
      maxPoints: 4,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 1, maxPoints: 4 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.6",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Ações de educação ambiental escolar (com projeto)",
      requirement: "Ações de educação ambiental em âmbito escolar.",
      requiredDocs: "Projeto Escolar/Educacional (sucinto, conforme Relatório Técnico, contendo problemática, justificativa, objetivos, culminância, metodologia, cronograma e avaliação) + Execução comprovada através de Relatório Operacional.",
      maxPoints: 12,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.7",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Eventos públicos temáticos de educação ambiental",
      requirement: "Atividades sociais de educação ambiental.",
      requiredDocs: "Relatório Operacional (com registro fotográfico datado, local de realização, público-alvo, lista de frequência, conteúdos abordados, relato sucinto, material divulgado) de eventos públicos temáticos.",
      maxPoints: 8,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 8 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.8",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Programa Guardiões Ambientais Mirins ou Brigadistas Mirins",
      requirement: "Implementação do Programa 'Guardiões Ambientais Mirins' ou 'Brigadistas Mirins': Programa de protagonismo estudantil, implementado em ao menos 01 escola da rede municipal em zona urbana + 01 em zona rural.",
      requiredDocs: "Projeto Pedagógico Simplificado + Relação dos Alunos Participantes + Relatório Fotográfico Comentado (georreferenciado e datado).",
      maxPoints: 14,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.9",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Congresso Municipal de Meio Ambiente (mínimo 2 dias)",
      requirement: "Realização do Congresso Municipal de Meio Ambiente: Evento (congresso, seminário ou fórum) aberto à comunidade, com duração mínima de 02 dias, para debater a pauta ambiental local.",
      requiredDocs: "Material de Divulgação + Programação Oficial + Lista de Presença + Ata ou Relatório Final do Evento + Registro Fotográfico (georreferenciado).",
      maxPoints: 14,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.10",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Campanha de combate à caça ilegal",
      requirement: "Campanha Educativa de Combate à Caça Ilegal: Conjunto de ações voltadas à conscientização da população, especialmente na zona rural.",
      requiredDocs: "Plano de Ação Simplificado + Cópia do Material Educativo Produzido + Relatório Fotográfico de ao menos 02 ações de sensibilização em locais diferentes (georreferenciadas).",
      maxPoints: 8,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "B.11",
      axis: "B",
      axisName: "Educação Ambiental",
      axisMinPoints: 50,
      description: "Página em rede social exclusiva de meio ambiente (mín. 4 posts/mês por 12 meses)",
      requirement: "Manutenção de Página Ativa em Rede Social sobre Meio Ambiente: página ou perfil em rede social de acesso público, exclusivamente dedicada à divulgação de informações e ações de educação ambiental.",
      requiredDocs: "Identificação da Página (link de acesso público + print) + Relatório de Atividade Continuada (mínimo 04 publicações mensais durante pelo menos 12 meses do período de apuração).",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── C — Redução do Desmatamento ───────────────────────────────────────────
    {
      id: "C.1",
      axis: "C",
      axisName: "Redução do Desmatamento e Recuperação de Áreas Degradadas",
      axisMinPoints: 50,
      description: "Redução do desmatamento (análise técnica SEMARH + link de mapas)",
      requirement: "Redução do desmatamento.",
      requiredDocs: "O município deverá postular o presente item, requerendo a análise e a emissão do Relatório Técnico referente ao Índice de Redução de Desmatamento Ilegal, conforme metodologia descrita no Termo de Referência vigente.",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: true,
      isReusable: false,
      validYears: null,
    },
    {
      id: "C.2",
      axis: "C",
      axisName: "Redução do Desmatamento e Recuperação de Áreas Degradadas",
      axisMinPoints: 50,
      description: "Identificação de áreas degradadas e monitoramento (2 anos)",
      requirement: "Identificação de áreas degradadas e seu monitoramento (2 anos).",
      requiredDocs: "Relatório Operacional (com identificação das áreas, coordenadas geográficas, diagnóstico do solo, da água e da vegetação, fatores que resultaram na degradação, registro fotográfico datado e georreferenciado, e análise da evolução da degradação) + Mapa georreferenciado + Quadro resumo de áreas degradadas + Assinatura de responsável técnico habilitado.",
      maxPoints: 10,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 2, maxPoints: 10 },
      hasMapLink: false,
      isReusable: false,
      validYears: 3,
    },
    {
      id: "C.3",
      axis: "C",
      axisName: "Redução do Desmatamento e Recuperação de Áreas Degradadas",
      axisMinPoints: 50,
      description: "Recuperação e/ou monitoramento de áreas degradadas",
      requirement: "Execução de ações de recuperação e/ou monitoramento (por dois anos) de áreas degradadas identificadas no item C.2.",
      requiredDocs: "Projeto técnico de Execução e Monitoramento vinculado às áreas identificadas no Item C.2 + Relatório Operacional (com ART) + Relatório Técnico de Monitoramento.",
      maxPoints: 24,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 6, maxPoints: 24 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "C.4",
      axis: "C",
      axisName: "Redução do Desmatamento e Recuperação de Áreas Degradadas",
      axisMinPoints: 50,
      description: "Criação e manutenção de Viveiro Municipal",
      requirement: "Criação e Manutenção de Viveiro Municipal.",
      requiredDocs: "Cópia da Lei ou Decreto Municipal de criação + Notas fiscais de insumos + Relatório fotográfico (mínimo 5 fotos georreferenciadas) + Inventário de mudas assinado por responsável técnico + Relatório de plantio das mudas.",
      maxPoints: 16,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "C.5",
      axis: "C",
      axisName: "Redução do Desmatamento e Recuperação de Áreas Degradadas",
      axisMinPoints: 50,
      description: "Plantio anual de mudas nativas (por faixa populacional)",
      requirement: "Plantio anual de mudas de espécies nativas em quantidade relativa à população do município, vedada a contagem de plantio em outros itens.",
      requiredDocs: "Projeto Técnico assinado por responsável habilitado (com ART) + Relatório Operacional + Mapa georreferenciado com distribuição dos pontos de plantio.",
      maxPoints: 30,
      scoringType: ScoringType.per_faixa,
      scoringConfig: {
        type: "population",
        faixas: [
          { minPop: 0, maxPop: 3000, levels: [{ level: 1, minQty: 250, points: 8 }, { level: 2, minQty: 500, points: 12 }, { level: 3, minQty: 900, points: 30 }] },
          { minPop: 3001, maxPop: 5000, levels: [{ level: 1, minQty: 350, points: 8 }, { level: 2, minQty: 650, points: 12 }, { level: 3, minQty: 1100, points: 30 }] },
          { minPop: 5001, maxPop: 10000, levels: [{ level: 1, minQty: 500, points: 8 }, { level: 2, minQty: 900, points: 12 }, { level: 3, minQty: 1500, points: 30 }] },
          { minPop: 10001, maxPop: 30000, levels: [{ level: 1, minQty: 650, points: 8 }, { level: 2, minQty: 1300, points: 12 }, { level: 3, minQty: 2000, points: 30 }] },
          { minPop: 30001, maxPop: 60000, levels: [{ level: 1, minQty: 900, points: 8 }, { level: 2, minQty: 1800, points: 12 }, { level: 3, minQty: 3000, points: 30 }] },
          { minPop: 60001, maxPop: 100000, levels: [{ level: 1, minQty: 1300, points: 8 }, { level: 2, minQty: 2500, points: 12 }, { level: 3, minQty: 4500, points: 30 }] },
          { minPop: 100001, maxPop: 300000, levels: [{ level: 1, minQty: 1800, points: 8 }, { level: 2, minQty: 2800, points: 12 }, { level: 3, minQty: 4500, points: 30 }] },
          { minPop: 300001, maxPop: null, levels: [{ level: 1, minQty: 2200, points: 8 }, { level: 2, minQty: 3800, points: 12 }, { level: 3, minQty: 6000, points: 30 }] },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── D — Queimadas, Solo e Biodiversidade ──────────────────────────────────
    {
      id: "D.1",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Brigada pública municipal de combate a incêndios florestais",
      requirement: "Existência de brigada pública municipal de combate a incêndios florestais.",
      requiredDocs: "Instrumento legal de criação da brigada + Relatório Operacional (endereço e descrição da sede física com fotos datadas e georreferenciadas + instrumento legal de nomeação dos componentes + vínculo municipal com Chefe da Brigada + treinamento comprovado + relação de EPIs e materiais + relatório de atividades preventivas e de combate).",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.2",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Plano Municipal de Mudanças Climáticas (PMMC)",
      requirement: "Plano Municipal de Mudanças Climáticas (PMMC).",
      requiredDocs: "Instrumento legal de aprovação e publicação do PMMC no Diário Oficial + Cópia integral do PMMC, contemplando estratégias e metas de mitigação e adaptação + Definição de responsabilidades e cronograma de execução.",
      maxPoints: 13,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "D.3",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Plano de Prevenção e Combate a Incêndios Florestais (PPCIF)",
      requirement: "Plano de Prevenção e Combate a Incêndios Florestais e Queimadas.",
      requiredDocs: "Instrumento legal de aprovação e publicação do PPCIF no Diário Oficial + Plano completo com abrangência municipal (diagnóstico, estrutura de governança, protocolos operacionais, inventário de recursos, plano de prevenção, de capacitação, de resposta e cronograma anual).",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.4",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Governança Municipal para Agenda 2030/ODS",
      requirement: "Institucionalização da Governança Municipal para a Agenda 2030 (ODS).",
      requiredDocs: "Carta-Compromisso 'Meu Município pelos ODS 2025-2030' + Lei ou Decreto de criação da Comissão Municipal para os ODS + Portaria de Nomeação dos Membros + Regimento Interno publicado em Diário Oficial + Plano de Ação e Diagnóstico Situacional.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.5",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Ações de proteção de solo",
      requirement: "Execução de ações de Proteção de Solo.",
      requiredDocs: "Relatório Operacional contendo diagnóstico da área, metodologia completa, técnicas e materiais empregados (cobertura, contenção, plantio direto, cercamento etc.) + ART + registros fotográficos georreferenciados antes, durante e depois.",
      maxPoints: 16,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.6",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Inventário faunístico e monitoramento de espécies silvestres",
      requirement: "Identificação e monitoramento de espécies da fauna silvestre no Município.",
      requiredDocs: "Inventário faunístico com amostragem sazonal + Relatório de Monitoramento, Atualização e Defesa das Espécies Silvestres + ART.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.7",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Bem-estar animal (abrigo, castração, atendimento veterinário)",
      requirement: "Execução de ações de promoção do bem-estar animal.",
      requiredDocs: "Relatório com descrição da estrutura física/quantitativo de animais (abrigo); e/ou relatório com quantitativo de animais atendidos em procedimentos de castração; e/ou relatório de atendimento médico veterinário gratuito.",
      maxPoints: 12,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "D.8",
      axis: "D",
      axisName: "Redução do Risco de Queimadas, Conservação do Solo e da Biodiversidade",
      axisMinPoints: 50,
      description: "Coordenação Municipal de Defesa Civil (CMDC)",
      requirement: "Estruturação da Coordenação Municipal de Defesa Civil (CMDC).",
      requiredDocs: "Lei ou Decreto de criação e regulamentação da CMDC + Plano Municipal de Ação da Defesa Civil publicado + Ato de nomeação do Coordenador Municipal + Ato de nomeação dos Técnicos Operacionais + Relatório Operacional de atividades.",
      maxPoints: 13,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── E — Proteção de Mananciais ─────────────────────────────────────────────
    {
      id: "E.1",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Cobertura de esgotamento sanitário (% × 0,15)",
      requirement: "Cobertura da rede de esgotamento sanitário.",
      requiredDocs: "Declaração emitida pela concessionária ou empresa de serviços de saneamento + Licença ambiental de Operação do órgão competente, em validade.",
      maxPoints: 12,
      scoringType: ScoringType.percentage,
      scoringConfig: { type: "percentage", coefficient: 0.15, maxPoints: 12 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.2",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Ações de proteção de nascentes",
      requirement: "Execução de ações de proteção de nascentes.",
      requiredDocs: "Projeto Técnico (com ART), contendo diagnóstico da área + Relatório Operacional (com ART) com localização das áreas, mapas e coordenadas + Comprovação documental de insumos + Mapas georreferenciados das áreas protegidas.",
      maxPoints: 16,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.3",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Proteção de águas subterrâneas",
      requirement: "Execução de ações de proteção e de recursos hídricos (águas subterrâneas).",
      requiredDocs: "Relatório operacional contendo diagnóstico, descrição e geolocalização da fonte + Descrição da ação de proteção proposta + metodologia + demonstração de resultados obtidos (com registro fotográfico datado e georreferenciado) + responsabilidade técnica.",
      maxPoints: 16,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.4",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Proteção e manutenção de águas superficiais",
      requirement: "Execução de ações de proteção e/ou manutenção de recursos hídricos (águas superficiais).",
      requiredDocs: "Projeto Técnico (com ART) + Relatório Operacional (com ART), contendo localização e diagnóstico das áreas com mapas, coordenadas e extensão + Comprovação documental de insumos e mudas + Mapas georreferenciados das áreas protegidas.",
      maxPoints: 16,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 4, maxPoints: 16 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.5",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Monitoramento da qualidade da água (poços municipais)",
      requirement: "Monitoramento da qualidade da água de mananciais subterrâneos de abastecimento público.",
      requiredDocs: "Relatório Técnico de Monitoramento, assinado por responsável habilitado, contendo laudos laboratoriais de análise da água (físico-química e bacteriológica) dos poços municipais, cobrindo no mínimo 2 trimestres distintos do ano de apuração + Identificação dos pontos de coleta georreferenciados.",
      maxPoints: 15,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 5, maxPoints: 15 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.6",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Regularização e outorga de captação subterrânea",
      requirement: "Regularização e eficiência na gestão de captação subterrânea.",
      requiredDocs: "Cópia da Portaria de Outorga de Direito de Uso (ou Dispensa de Outorga) emitida pelo órgão competente para os poços de domínio municipal vigentes no ano de apuração, conforme inventário do item E.7.",
      maxPoints: 13,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "E.7",
      axis: "E",
      axisName: "Proteção de Mananciais de Abastecimento Público",
      axisMinPoints: 50,
      description: "Cadastro técnico municipal de poços e fontes",
      requirement: "Cadastro Técnico Municipal de Poços e Fontes.",
      requiredDocs: "Inventário Hidrogeológico Municipal, apresentado em formato de mapa georreferenciado e planilha técnica, contendo a localização de todos os pontos de captação de domínio municipal, com dados de vazão, profundidade e status de operação.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── F — Controle da Poluição ───────────────────────────────────────────────
    {
      id: "F.1",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate à poluição sonora",
      requirement: "Campanhas educativas ou de combate e controle da poluição sonora.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades, locais de realização, registro fotográfico datado e período de realização mínimo de 4 dias de campanha, distribuídos em 2 semestres do ano de apuração.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.2",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate à poluição atmosférica",
      requirement: "Campanhas educativas ou de combate da poluição atmosférica e mudanças climáticas.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades, locais de realização, registro fotográfico datado e período de realização mínimo de 4 dias de campanha, distribuídos em 2 semestres do ano de apuração.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.3",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Campanhas de combate à poluição visual",
      requirement: "Campanhas educativas ou de combate e controle da poluição visual.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades, locais de realização, registro fotográfico datado e período de realização mínimo de 4 dias de campanha, distribuídos em 2 semestres do ano de apuração.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.4",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Estruturação da fiscalização ambiental municipal",
      requirement: "Planejamento e estruturação da fiscalização ambiental municipal.",
      requiredDocs: "Relatório Operacional descrevendo quadro de funcionários de fiscalização (conforme Lei Federal n. 9.605/98, art. 70, §1º), com comprovação de vínculo + comprovante de designação da autoridade julgadora + planejamento de atividades de fiscalização preventiva.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.5",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Fiscalização de poluição sonora (≥6 dias/ano, 3 quadrimestres)",
      requirement: "Exercício da fiscalização de fontes de poluição sonora.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades de fiscalização relacionadas à poluição sonora em pelo menos 06 dias distintos no período de apuração, distribuídos em pelo menos 3 quadrimestres distintos, com fotos datadas e georreferenciadas.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.6",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Fiscalização de poluição visual (≥6 dias/ano, 3 quadrimestres)",
      requirement: "Exercício da fiscalização de fontes de poluição visual.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades de fiscalização relacionadas à poluição visual em pelo menos 06 dias distintos no período de apuração, distribuídos em pelo menos 3 quadrimestres distintos, com fotos e descrição de processos de apuração de irregularidades.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.7",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Fiscalização de poluição atmosférica (≥6 dias/ano, 3 quadrimestres)",
      requirement: "Exercício da fiscalização de fontes de poluição atmosférica.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades de fiscalização relacionadas à poluição atmosférica em pelo menos 06 dias distintos no período de apuração, distribuídos em pelo menos 3 quadrimestres distintos, contendo fotos e descrição de processos de apuração de irregularidades.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "F.8",
      axis: "F",
      axisName: "Controle da Poluição e Regularidade Ambiental Municipal",
      axisMinPoints: 50,
      description: "Certidão Negativa de Débitos Ambientais (SEMARH)",
      requirement: "Comprovação de Regularidade Ambiental Municipal.",
      requiredDocs: "Apresentação de Certidão Negativa de Débitos Ambientais, emitida pelo órgão ambiental competente (SEMARH), válida dentro do período de apuração do certame.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── G — Edificações Irregulares ───────────────────────────────────────────
    {
      id: "G.1",
      axis: "G",
      axisName: "Edificações Irregulares",
      axisMinPoints: 50,
      description: "Estrutura institucional de controle de uso do solo",
      requirement: "Estrutura institucional de controle da aplicação da lei municipal de uso e ocupação do solo.",
      requiredDocs: "Instrumento legal de instituição da política municipal de uso e ocupação do solo + instrumento legal de instituição do órgão designado para o controle + instrumento legal de nomeação do quadro funcional + instrumento legal de criação do conselho municipal de desenvolvimento urbano.",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "G.2",
      axis: "G",
      axisName: "Edificações Irregulares",
      axisMinPoints: 50,
      description: "Controle efetivo de uso do solo (licenças urbanísticas)",
      requirement: "Controle efetivo de uso e ocupação do solo do município (quando possuir lei municipal de uso e ocupação do solo).",
      requiredDocs: "Relatório operacional (detalhamento das licenças urbanísticas emitidas no período de apuração: número da licença, interessado e data de validade).",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "G.3",
      axis: "G",
      axisName: "Edificações Irregulares",
      axisMinPoints: 50,
      description: "Fiscalização de irregularidades no uso do solo (≥6 dias/3 quadrimestres)",
      requirement: "Exercício de fiscalização de irregularidades na aplicação da norma de uso e ocupação do solo.",
      requiredDocs: "Relatório Operacional contendo a descrição das atividades de fiscalização relacionadas à inadequação da norma de uso e ocupação do solo, em pelo menos 06 dias distintos, distribuídos em pelo menos 3 quadrimestres distintos.",
      maxPoints: 25,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "G.4",
      axis: "G",
      axisName: "Edificações Irregulares",
      axisMinPoints: 50,
      description: "Proposta de requalificação urbana em execução",
      requirement: "Proposta de requalificação urbana em execução durante o período de apuração.",
      requiredDocs: "Cópia do plano de requalificação urbana + relatório operacional + comprovação de responsabilidade técnica.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "G.5",
      axis: "G",
      axisName: "Edificações Irregulares",
      axisMinPoints: 50,
      description: "Mapeamento atualizado de assentamentos precários",
      requirement: "Mapeamento atualizado de assentamentos precários e edificações irregulares.",
      requiredDocs: "Diagnóstico do território municipal, no período de apuração, considerando variáveis de edificações irregulares e assentamentos precários (renda domiciliar, situação fundiária, domínio da área, população, infraestrutura urbana, padrão viário, padrão de lotes, áreas de risco, etc.).",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── H — Unidades de Conservação ───────────────────────────────────────────
    {
      id: "H.1",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "Incidência de UC federal/estadual no território",
      requirement: "Incidência territorial de Unidade de Conservação instituída por outro ente da federação (federal/estadual).",
      requiredDocs: "Ato normativo de criação, conforme legislação federal e/ou estadual + relatório apresentando comprovação de incidência territorial.",
      maxPoints: 20,
      scoringType: ScoringType.per_faixa,
      scoringConfig: {
        type: "territory",
        ranges: [
          { minPct: 0, maxPct: 25, points: 5 },
          { minPct: 25, maxPct: 50, points: 10 },
          { minPct: 50, maxPct: 75, points: 15 },
          { minPct: 75, maxPct: null, points: 20 },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.2",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "Ações conjuntas com UC estadual/federal",
      requirement: "Execução de ações conjuntas com as Unidades de Conservação Estadual e/ou Federal quando impossível criar Unidades de Conservação Municipal.",
      requiredDocs: "Relatório técnico com descrição da ação de cooperação para gestão da UC + apresentação de metodologia + demonstração de resultados obtidos (com registro fotográfico datado e georreferenciado).",
      maxPoints: 60,
      scoringType: ScoringType.per_unit,
      scoringConfig: { type: "per_unit", unitValue: 10, maxPoints: 60 },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.3",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "UC municipal no território",
      requirement: "Incidência territorial de unidade de conservação (municipal).",
      requiredDocs: "Ato normativo de criação, observado os parâmetros da legislação federal e estadual + relatório apresentando comprovação de incidência territorial.",
      maxPoints: 45,
      scoringType: ScoringType.per_faixa,
      scoringConfig: {
        type: "territory",
        ranges: [
          { minPct: 0, maxPct: 25, points: 30 },
          { minPct: 25, maxPct: 50, points: 35 },
          { minPct: 50, maxPct: 75, points: 40 },
          { minPct: 75, maxPct: null, points: 45 },
        ],
      },
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.4",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "Sede administrativa de UC municipal",
      requirement: "Estrutura física de unidade de conservação municipal: existência de sede administrativa.",
      requiredDocs: "Relatório operacional com descrição dos equipamentos e instalações localizadas na unidade de conservação municipal, com registro fotográfico datado.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.5",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "Plano de manejo de UC municipal",
      requirement: "Instituição de plano de manejo da unidade de conservação municipal.",
      requiredDocs: "Cópia do plano de manejo da unidade de conservação municipal aprovado pela SEMARH + publicação do ato de aprovação + relatório operacional de execução do plano de manejo, com registro fotográfico datado.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.6",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "Conselho gestor de UC municipal",
      requirement: "Existência do conselho gestor da unidade de conservação municipal.",
      requiredDocs: "Ato legal de criação do conselho conforme §6º, art. 17 do Decreto Federal nº 4.340/2002 + instrumento legal de nomeação dos membros do conselho + atas das reuniões do conselho.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "H.7",
      axis: "H",
      axisName: "Unidades de Conservação",
      axisMinPoints: 50,
      description: "UC completa com estrutura (H.3+H.4+H.5+H.6) — bônus",
      requirement: "Criação de Unidade de conservação com estrutura completa abrangendo os itens H.3 a H.6.",
      requiredDocs: "Todos os documentos comprobatórios dos itens H.3 a H.6.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },

    // ── I — Legislação Ambiental ───────────────────────────────────────────────
    {
      id: "I.1",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Política Municipal de Combate às Mudanças Climáticas",
      requirement: "Política Municipal de Combate às Mudanças Climáticas.",
      requiredDocs: "Legislação ambiental municipal sobre o tema, descrevendo ações ambientais, com objetivos a serem perseguidos, devidamente publicada.",
      maxPoints: 8,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.2",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Cobrança por coleta de resíduos (taxa municipal)",
      requirement: "Instituição de cobrança por serviço de coleta, remoção e destinação de resíduos sólidos e sua respectiva cobrança.",
      requiredDocs: "Legislação municipal sobre o tema, conforme o art. 29, inciso II, da Lei Federal nº 11.445/2007 + Documento oficial apto a comprovar as receitas decorrentes da cobrança da Taxa.",
      maxPoints: 20,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.3",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Política Municipal de Meio Ambiente",
      requirement: "Política Municipal de Meio Ambiente.",
      requiredDocs: "Legislação ambiental municipal sobre o tema, descrevendo ações ambientais, com objetivos a serem perseguidos, devidamente publicada.",
      maxPoints: 10,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.4",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Política Municipal de Educação Ambiental",
      requirement: "Política Municipal de Educação Ambiental.",
      requiredDocs: "Legislação ambiental municipal sobre o tema, devidamente publicada.",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.5",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Órgão Municipal habilitado para licenciamento ambiental",
      requirement: "Órgão Municipal de Meio Ambiente Habilitado para o Licenciamento.",
      requiredDocs: "Cópia da Lei de Criação do Órgão Executivo Municipal + cópia do Ato ou Decreto de nomeação do Secretário e Técnicos do Órgão Municipal de Meio Ambiente com formação compatível + Declaração Emitida Pela SEMARH que comprove a municipalização do licenciamento + Relatório Operacional contendo todas as licenças expedidas no ano de apuração.",
      maxPoints: 12,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: false,
      validYears: null,
    },
    {
      id: "I.6",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Fundo Municipal do Meio Ambiente",
      requirement: "Fundo Municipal do Meio Ambiente.",
      requiredDocs: "Cópia da Lei de Criação do Fundo Municipal do Meio Ambiente + cópia do decreto de regulamentação + cópia das atas das reuniões + cópia do Termo de posse dos conselheiros do Conselho Gestor do Fundo.",
      maxPoints: 5,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.7",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Legislação de controle da poluição sonora",
      requirement: "Legislação de controle da poluição sonora.",
      requiredDocs: "Cópia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.8",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Legislação de controle da poluição visual",
      requirement: "Legislação de controle da poluição visual.",
      requiredDocs: "Cópia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.9",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Legislação de controle da poluição atmosférica",
      requirement: "Legislação de controle da poluição atmosférica.",
      requiredDocs: "Cópia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.10",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Legislações específicas sobre licenciamento ambiental municipal",
      requirement: "Legislações específicas sobre o licenciamento ambiental municipal.",
      requiredDocs: "Cópia dos instrumentos legais devidamente publicados.",
      maxPoints: 15,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
    {
      id: "I.11",
      axis: "I",
      axisName: "Legislação sobre a Política Municipal de Meio Ambiente",
      axisMinPoints: 50,
      description: "Legislação de promoção do bem-estar animal",
      requirement: "Legislação de promoção do bem-estar animal.",
      requiredDocs: "Cópia do instrumento legal devidamente publicado.",
      maxPoints: 6,
      scoringType: ScoringType.fixed,
      scoringConfig: Prisma.JsonNull,
      hasMapLink: false,
      isReusable: true,
      validYears: null,
    },
  ];

  // Upsert de todos os critérios
  for (const item of criteria) {
  await prisma.criteria.upsert({
    where: { id: item.id },
    update: item,
    create: item,
  });
}
  console.log(`✅ ${criteria.length} critérios criados/atualizados`);

  console.log("\n🎉 Seed concluído com sucesso!");
  console.log("─────────────────────────────────────────");
  console.log("Admin:", admin.email);
  console.log("Senha provisória: Admin@2026!");
  console.log("─────────────────────────────────────────");
}

main()
  .catch((e) => {
    console.error("❌ Erro no seed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
